import { z } from "zod";

// @autolight/config registry (T-CFG-01). Generated from
// docs/finish/03-config-and-decisions.md section 3 by
// `yarn workspace @autolight/config run export`. Do not hand-edit: edit the
// catalog, rerun export, commit both. 240 keys.

export interface KeyDef {
  key: string;
  type: "string" | "number" | "boolean" | "json";
  defaultRaw: string;
  unit: string;
  range: string;
  receipt: string;
  liveSafe: boolean;
  scope: "app" | "venue" | "device" | "style" | "session";
}

export const KEYS: readonly KeyDef[] = [
  { key: "runtime.host", type: "string", defaultRaw: "worker-thread", unit: "enum DS-07", range: "see DS-07", receipt: "spec 56", liveSafe: false, scope: "app" },
  { key: "runtime.clock.tickHz", type: "number", defaultRaw: "60", unit: "Hz", range: "30 to 120", receipt: "spec 117", liveSafe: false, scope: "app" },
  { key: "runtime.clock.timerStrategy", type: "string", defaultRaw: "hybrid", unit: "enum DS-08", range: "see DS-08", receipt: "unmeasured (T-ARC-06)", liveSafe: false, scope: "app" },
  { key: "runtime.clock.spinWindowMs", type: "number", defaultRaw: "1.5", unit: "ms", range: "0 to 5", receipt: "unmeasured (T-ARC-06)", liveSafe: false, scope: "app" },
  { key: "runtime.snapshot.uiRateHz", type: "number", defaultRaw: "30", unit: "Hz", range: "10 to 60", receipt: "unmeasured (T-ARC-04)", liveSafe: true, scope: "app" },
  { key: "runtime.snapshot.maxBytes", type: "number", defaultRaw: "262144", unit: "bytes", range: "16384 to 4194304", receipt: "unmeasured (T-ARC-04)", liveSafe: true, scope: "app" },
  { key: "runtime.crash.holdMs", type: "number", defaultRaw: "2000", unit: "ms", range: "0 to 30000", receipt: "unmeasured (T-ARC-03)", liveSafe: true, scope: "app" },
  { key: "runtime.estimator.correctionGain", type: "number", defaultRaw: "0.15", unit: "ratio per tick", range: "0.01 to 1", receipt: "unmeasured (T-RUN-02)", liveSafe: true, scope: "app" },
  { key: "runtime.estimator.maxSlewBeatsPerSec", type: "number", defaultRaw: "0.08", unit: "beats/s", range: "0 to 1", receipt: "unmeasured (T-RUN-02)", liveSafe: true, scope: "app" },
  { key: "runtime.estimator.maxErrorMs", type: "number", defaultRaw: "20", unit: "ms", range: "1 to 200", receipt: "unmeasured target", liveSafe: true, scope: "app" },
  { key: "runtime.seek.thresholdBeats", type: "number", defaultRaw: "0.5", unit: "beats", range: "0.1 to 16", receipt: "unmeasured (was 8, `show-runtime/src/index.ts:42`)", liveSafe: true, scope: "app" },
  { key: "runtime.seek.thresholdMs", type: "number", defaultRaw: "150", unit: "ms", range: "10 to 2000", receipt: "unmeasured (was 250, `dj-core/src/index.ts:12`)", liveSafe: true, scope: "app" },
  { key: "runtime.scratch.rateDeviation", type: "number", defaultRaw: "0.5", unit: "ratio", range: "0.05 to 2", receipt: "unmeasured (T-RUN-05)", liveSafe: true, scope: "app" },
  { key: "runtime.scratch.minReversalsPerSec", type: "number", defaultRaw: "2", unit: "1/s", range: "0 to 20", receipt: "unmeasured", liveSafe: true, scope: "app" },
  { key: "runtime.scratch.resyncAt", type: "string", defaultRaw: "bar", unit: "enum beat, bar, phrase", range: "", receipt: "spec 61 \"next sensible boundary\"", liveSafe: true, scope: "app" },
  { key: "runtime.loop.variation", type: "string", defaultRaw: "alternate-ab", unit: "enum none, alternate-ab, rotate-3", range: "", receipt: "spec 59", liveSafe: true, scope: "app" },
  { key: "runtime.roll.degradeOrder", type: "json", defaultRaw: "[\"pulse\",\"contraction\",\"impact\"]", unit: "list", range: "", receipt: "spec 60", liveSafe: true, scope: "app" },
  { key: "runtime.health.extrapolateMs", type: "number", defaultRaw: "500", unit: "ms", range: "", receipt: "spec 105", liveSafe: true, scope: "app" },
  { key: "runtime.health.holdMs", type: "number", defaultRaw: "2000", unit: "ms", range: "", receipt: "spec 105", liveSafe: true, scope: "app" },
  { key: "runtime.override.resumeDefault", type: "string", defaultRaw: "bar", unit: "enum", range: "beat, bar, phrase, immediate", receipt: "spec 134", liveSafe: true, scope: "app" },
  { key: "runtime.override.whiteIntensity", type: "number", defaultRaw: "1.0", unit: "ratio", range: "0 to 1", receipt: "spec 48", liveSafe: true, scope: "app" },
  { key: "runtime.override.masterIntensity", type: "number", defaultRaw: "1.0", unit: "ratio", range: "0 to 1", receipt: "spec 94", liveSafe: true, scope: "app" },
  { key: "runtime.fastPath.budgetMs", type: "number", defaultRaw: "100", unit: "ms", range: "", receipt: "unmeasured target (spec 138 \"instantly\")", liveSafe: false, scope: "app" },
  { key: "runtime.upgrade.boundary", type: "string", defaultRaw: "phrase", unit: "enum section, phrase, bar", range: "", receipt: "spec 140", liveSafe: true, scope: "app" },
  { key: "ops.startup.budgetMs", type: "number", defaultRaw: "10000", unit: "ms", range: "1000 to 60000", receipt: "unmeasured target (spec 132)", liveSafe: false, scope: "app" },
  { key: "runtime.adaptive.phraseBeats", type: "number", defaultRaw: "32", unit: "beats", range: "8 to 64", receipt: "unmeasured", liveSafe: true, scope: "app" },
  { key: "runtime.adaptive.cooldownPhrases", type: "number", defaultRaw: "2", unit: "phrases", range: "0 to 8", receipt: "was 2 (`reactive-audio/src/index.ts:35`)", liveSafe: true, scope: "app" },
  { key: "runtime.adaptive.engine", type: "string", defaultRaw: "combined", unit: "enum DS-28", range: "", receipt: "owner", liveSafe: true, scope: "app" },
  { key: "runtime.adaptive.minLooks", type: "number", defaultRaw: "24", unit: "count", range: "1 to 500", receipt: "unmeasured", liveSafe: true, scope: "app" },
  { key: "mixer.crossfader.curve", type: "string", defaultRaw: "source", unit: "enum source, linear, constant-power, sharp-cut", range: "", receipt: "spec 63", liveSafe: true, scope: "style" },
  { key: "mixer.crossfader.assignment", type: "json", defaultRaw: "{ \"1\": \"A\", \"2\": \"B\", \"3\": \"THRU\", \"4\": \"THRU\" }", unit: "map", range: "A, B, THRU", receipt: "spec 63", liveSafe: true, scope: "style" },
  { key: "mixer.weight.masterBonus", type: "number", defaultRaw: "0.1", unit: "ratio", range: "0 to 0.5", receipt: "unmeasured", liveSafe: true, scope: "style" },
  { key: "mixer.intro.paletteAt", type: "number", defaultRaw: "0.05", unit: "weight", range: "0 to 1", receipt: "was hardcoded (`show-mixer/src/index.ts:31`)", liveSafe: true, scope: "style" },
  { key: "mixer.intro.rhythmAt", type: "number", defaultRaw: "0.3", unit: "weight", range: "0 to 1", receipt: "was hardcoded", liveSafe: true, scope: "style" },
  { key: "mixer.intro.impactsAt", type: "number", defaultRaw: "0.7", unit: "weight", range: "0 to 1", receipt: "was hardcoded", liveSafe: true, scope: "style" },
  { key: "mixer.blackout.policy", type: "string", defaultRaw: "auto", unit: "enum DS-18", range: "", receipt: "spec 66", liveSafe: true, scope: "style" },
  { key: "mixer.blackout.otherDeckThreshold", type: "number", defaultRaw: "0.3", unit: "weight", range: "0 to 1", receipt: "was hardcoded (`show-mixer/src/index.ts:25`)", liveSafe: true, scope: "style" },
  { key: "mixer.owner.hysteresis", type: "number", defaultRaw: "0.1", unit: "ratio", range: "0 to 0.5", receipt: "unmeasured", liveSafe: true, scope: "style" },
  { key: "mixer.owner.factorWeights", type: "json", defaultRaw: "{ weight: 1, master: 0.3, confidence: 0.5, strength: 1, significance: 0.5 }", unit: "map", range: "", receipt: "unmeasured (spec 65 factors)", liveSafe: true, scope: "style" },
  { key: "mixer.blendSpace", type: "string", defaultRaw: "oklab-hue-linear-intensity", unit: "enum DS-09", range: "", receipt: "spec 64 (combined mode)", liveSafe: true, scope: "style" },
  { key: "render.gammaDefault", type: "number", defaultRaw: "2.2", unit: "exponent", range: "1 to 3", receipt: "spec 49 approximation; per device from calibration", liveSafe: true, scope: "style" },
  { key: "render.antialias.subCell", type: "boolean", defaultRaw: "true", unit: "bool", range: "", receipt: "owner room request", liveSafe: true, scope: "style" },
  { key: "render.singleZone.representative", type: "string", defaultRaw: "area-weighted-mean-oklab", unit: "enum mean-linear, area-weighted-mean-oklab, dominant, center-cell", range: "", receipt: "unmeasured", liveSafe: true, scope: "style" },
  { key: "render.latency.mode", type: "string", defaultRaw: "measured-else-sku", unit: "enum DS-17", range: "", receipt: "spec 55", liveSafe: true, scope: "style" },
  { key: "render.impact.defaultMs", type: "number", defaultRaw: "90", unit: "ms", range: "20 to 500", receipt: "spec 36 example", liveSafe: true, scope: "style" },
  { key: "render.strobe.maxHz", type: "number", defaultRaw: "12", unit: "Hz", range: "1 to 30", receipt: "unmeasured; also capped by fixture fps", liveSafe: true, scope: "style" },
  { key: "render.tickBudgetMs", type: "number", defaultRaw: "4", unit: "ms per tick (2,000 cells, two decks)", range: "1 to 16", receipt: "unmeasured target", liveSafe: false, scope: "style" },
  { key: "planner.version", type: "string", defaultRaw: "read-only", unit: "string", range: "", receipt: "code", liveSafe: false, scope: "style" },
  { key: "planner.mode", type: "string", defaultRaw: "rules-with-veto", unit: "enum DS-19", range: "", receipt: "spec 113 (combined mode)", liveSafe: false, scope: "style" },
  { key: "planner.sectionEnergy", type: "json", defaultRaw: "{intro:.3, verse:.45, prechorus:.6, build:.8, drop:1, chorus:.9, breakdown:.25, bridge:.5, instrumental:.6, solo:.7, outro:.3, transition:.5, unknown:.5}", unit: "map", range: "", receipt: "was `SECTION_ENERGY` (`show-planner/src/index.ts:65-69`)", liveSafe: true, scope: "style" },
  { key: "planner.drop.minConfidence", type: "number", defaultRaw: "0.5", unit: "ratio", range: "", receipt: "unmeasured", liveSafe: true, scope: "style" },
  { key: "planner.drop.stages", type: "json", defaultRaw: "[8,8,8,4,4]", unit: "beats list", range: "", receipt: "spec 36 example", liveSafe: true, scope: "style" },
  { key: "planner.drop.preDarknessBeats", type: "number", defaultRaw: "1", unit: "beats", range: "", receipt: "spec 35, 36", liveSafe: true, scope: "style" },
  { key: "planner.drop.burstBeats", type: "number", defaultRaw: "2", unit: "beats", range: "", receipt: "spec 36", liveSafe: true, scope: "style" },
  { key: "planner.restraint.whiteHitMinBeats", type: "number", defaultRaw: "16", unit: "beats", range: "", receipt: "was 8 with \"ponytail\"", liveSafe: true, scope: "style" },
  { key: "planner.restraint.blackoutMinBeats", type: "number", defaultRaw: "32", unit: "beats", range: "", receipt: "unmeasured", liveSafe: true, scope: "style" },
  { key: "planner.restraint.strobeMaxDuty", type: "number", defaultRaw: "0.08", unit: "ratio", range: "", receipt: "unmeasured", liveSafe: true, scope: "style" },
  { key: "planner.restraint.paletteChangeMinBeats", type: "number", defaultRaw: "16", unit: "beats", range: "", receipt: "spec 114", liveSafe: true, scope: "style" },
  { key: "planner.restraint.patternRepeatMax", type: "number", defaultRaw: "4", unit: "count", range: "", receipt: "unmeasured", liveSafe: true, scope: "style" },
  { key: "planner.restraint.sectionImpactMax", type: "number", defaultRaw: "3", unit: "count", range: "", receipt: "unmeasured", liveSafe: true, scope: "style" },
  { key: "planner.restraint.trackImpactMax", type: "number", defaultRaw: "12", unit: "count", range: "", receipt: "unmeasured", liveSafe: true, scope: "style" },
  { key: "planner.contrast.breakdownMaxMean", type: "number", defaultRaw: "0.3", unit: "ratio", range: "", receipt: "unmeasured", liveSafe: true, scope: "style" },
  { key: "planner.recurrence.similarityThreshold", type: "number", defaultRaw: "0.8", unit: "cosine", range: "", receipt: "unmeasured", liveSafe: true, scope: "style" },
  { key: "planner.candidates.perSection", type: "number", defaultRaw: "4", unit: "count", range: "", receipt: "DS-19", liveSafe: true, scope: "style" },
  { key: "planner.chase.basePeriodBeats", type: "number", defaultRaw: "8", unit: "beats", range: "", receipt: "was hardcoded", liveSafe: true, scope: "style" },
  { key: "planner.palette.minDistance", type: "number", defaultRaw: "0.12", unit: "OKLab distance", range: "", receipt: "unmeasured", liveSafe: true, scope: "style" },
  { key: "planner.events.minConfidence", type: "string", defaultRaw: "per event type map, 0.5 default", unit: "ratio", range: "", receipt: "unmeasured", liveSafe: true, scope: "style" },
  { key: "planner.evaluation.bounds", type: "string", defaultRaw: "map of the ten spec 115 diagnostics to allowed ranges", unit: "map", range: "", receipt: "unmeasured", liveSafe: true, scope: "style" },
  { key: "planner.compile.budgetMs", type: "number", defaultRaw: "2000", unit: "ms p95", range: "", receipt: "unmeasured target", liveSafe: false, scope: "style" },
  { key: "planner.validation.rejectOn", type: "json", defaultRaw: "[\"exclusive-overlap\",\"negative-duration\",\"out-of-range\",\"unsupported-capability\"]", unit: "list", range: "", receipt: "spec 114", liveSafe: false, scope: "style" },
  { key: "audio.capture.host", type: "string", defaultRaw: "audio-window", unit: "enum DS-14", range: "", receipt: "owner", liveSafe: false, scope: "app" },
  { key: "audio.capture.deviceId", type: "string", defaultRaw: "\"\" (none)", unit: "string", range: "", receipt: "user", liveSafe: true, scope: "app" },
  { key: "audio.fftSize", type: "number", defaultRaw: "2048", unit: "samples", range: "", receipt: "unmeasured", liveSafe: false, scope: "app" },
  { key: "audio.melBands", type: "number", defaultRaw: "24", unit: "count", range: "", receipt: "unmeasured", liveSafe: false, scope: "app" },
  { key: "audio.agc.rise", type: "number", defaultRaw: "0.3", unit: "ratio", range: "", receipt: "was hardcoded (`reactive-audio/src/index.ts:11`)", liveSafe: true, scope: "app" },
  { key: "audio.agc.decay", type: "number", defaultRaw: "0.05", unit: "ratio", range: "", receipt: "was hardcoded", liveSafe: true, scope: "app" },
  { key: "audio.agc.target", type: "number", defaultRaw: "0.5", unit: "ratio", range: "", receipt: "was hardcoded", liveSafe: true, scope: "app" },
  { key: "audio.onset.threshold", type: "number", defaultRaw: "1.5", unit: "z-score", range: "", receipt: "unmeasured", liveSafe: true, scope: "app" },
  { key: "audio.overlay.cap", type: "number", defaultRaw: "0.2", unit: "ratio", range: "", receipt: "was `MAX_OVERLAY_GAIN`; final amount = cap times `style.reactiveAmount`", liveSafe: true, scope: "app" },
  { key: "analysis.worker.concurrency", type: "number", defaultRaw: "1", unit: "jobs", range: "", receipt: "unmeasured", liveSafe: false, scope: "app" },
  { key: "analysis.worker.restartBackoffMs", type: "json", defaultRaw: "[1000, 30000]", unit: "ms min/max", range: "", receipt: "unmeasured", liveSafe: false, scope: "app" },
  { key: "analysis.worker.jobTimeoutMs", type: "number", defaultRaw: "900000", unit: "ms", range: "", receipt: "unmeasured", liveSafe: false, scope: "app" },
  { key: "analysis.worker.heartbeatMs", type: "number", defaultRaw: "5000", unit: "ms", range: "", receipt: "unmeasured", liveSafe: false, scope: "app" },
  { key: "analysis.cacheDir", type: "string", defaultRaw: "<userData>/analysis-cache", unit: "path", range: "", receipt: "spec 82", liveSafe: false, scope: "app" },
  { key: "analysis.device", type: "string", defaultRaw: "auto", unit: "enum auto, cpu, cuda", range: "", receipt: "spec 16", liveSafe: false, scope: "app" },
  { key: "analysis.ml.enabled", type: "boolean", defaultRaw: "true", unit: "bool", range: "", receipt: "spec 16", liveSafe: false, scope: "app" },
  { key: "analysis.ml.modelCacheDir", type: "string", defaultRaw: "<userData>/models", unit: "path", range: "", receipt: "T-ANA-05", liveSafe: false, scope: "app" },
  { key: "analysis.ml.offlineOnly", type: "string", defaultRaw: "true during Live", unit: "bool", range: "", receipt: "spec 110", liveSafe: false, scope: "app" },
  { key: "analysis.stems.mode", type: "string", defaultRaw: "fusion", unit: "enum DS-10", range: "", receipt: "owner", liveSafe: false, scope: "app" },
  { key: "analysis.structure.mode", type: "string", defaultRaw: "fused", unit: "enum DS-11", range: "", receipt: "spec 19", liveSafe: false, scope: "app" },
  { key: "analysis.metrical.mode", type: "string", defaultRaw: "both", unit: "enum DS-12", range: "", receipt: "spec 17", liveSafe: false, scope: "app" },
  { key: "analysis.frame.hop", type: "number", defaultRaw: "512", unit: "samples", range: "", receipt: "unmeasured (was 1024)", liveSafe: false, scope: "app" },
  { key: "analysis.frame.size", type: "number", defaultRaw: "2048", unit: "samples", range: "", receipt: "was hardcoded", liveSafe: false, scope: "app" },
  { key: "analysis.bands", type: "json", defaultRaw: "{bass:[20,150], lowMid:[150,500], mid:[500,2000], high:[2000,20000]}", unit: "Hz", range: "", receipt: "was hardcoded (`stems.py:51-59`)", liveSafe: false, scope: "app" },
  { key: "analysis.build.windows", type: "json", defaultRaw: "[8,16,32]", unit: "beats", range: "", receipt: "spec 23", liveSafe: false, scope: "app" },
  { key: "analysis.drop.minJump", type: "number", defaultRaw: "0.25", unit: "relative", range: "", receipt: "was hardcoded (`structure.py:81`)", liveSafe: false, scope: "app" },
  { key: "analysis.drop.minVotes", type: "number", defaultRaw: "3", unit: "count", range: "", receipt: "was hardcoded", liveSafe: false, scope: "app" },
  { key: "analysis.drop.minConfidence", type: "number", defaultRaw: "0.6", unit: "ratio", range: "", receipt: "was hardcoded", liveSafe: false, scope: "app" },
  { key: "analysis.silence.level", type: "number", defaultRaw: "0.05", unit: "ratio of max", range: "", receipt: "was hardcoded (`worker.py:47`)", liveSafe: false, scope: "app" },
  { key: "analysis.fakeDrop.gapBeats", type: "json", defaultRaw: "[1,4]", unit: "beats", range: "", receipt: "spec 25", liveSafe: false, scope: "app" },
  { key: "analysis.gridWarning.toleranceMs", type: "number", defaultRaw: "50", unit: "ms", range: "", receipt: "was 0.05 s", liveSafe: false, scope: "app" },
  { key: "analysis.gridWarning.minAnchors", type: "number", defaultRaw: "32", unit: "count", range: "", receipt: "unmeasured", liveSafe: false, scope: "app" },
  { key: "analysis.decode.resampler", type: "string", defaultRaw: "soxr", unit: "enum soxr, swr", range: "", receipt: "unmeasured", liveSafe: false, scope: "app" },
  { key: "analysis.beatthis.invoke", type: "string", defaultRaw: "api", unit: "enum api, cli", range: "", receipt: "upstream README", liveSafe: false, scope: "app" },
  { key: "analysis.aggregate.subdivisions", type: "number", defaultRaw: "4", unit: "per beat", range: "", receipt: "unmeasured", liveSafe: false, scope: "app" },
  { key: "analysis.stems.keepAudio", type: "boolean", defaultRaw: "false", unit: "bool", range: "", receipt: "disk budget", liveSafe: false, scope: "app" },
  { key: "govee.lan.engine", type: "string", defaultRaw: "auto", unit: "enum DS-02", range: "", receipt: "owner", liveSafe: false, scope: "app" },
  { key: "govee.lan.ports.scan", type: "number", defaultRaw: "4001", unit: "port", range: "", receipt: "Govee WLAN guide", liveSafe: false, scope: "app" },
  { key: "govee.lan.ports.reply", type: "number", defaultRaw: "4002", unit: "port", range: "", receipt: "Govee WLAN guide", liveSafe: false, scope: "app" },
  { key: "govee.lan.ports.control", type: "number", defaultRaw: "4003", unit: "port", range: "", receipt: "Govee WLAN guide", liveSafe: false, scope: "app" },
  { key: "govee.lan.interfaces", type: "json", defaultRaw: "[] (all eligible)", unit: "list of interface names", range: "", receipt: "spec 111", liveSafe: false, scope: "app" },
  { key: "govee.lan.discovery.multicast", type: "boolean", defaultRaw: "true", unit: "bool", range: "", receipt: "govee2mqtt `lan_api.rs`", liveSafe: false, scope: "app" },
  { key: "govee.lan.discovery.perInterfaceBroadcast", type: "boolean", defaultRaw: "true", unit: "bool", range: "", receipt: "govee2mqtt", liveSafe: false, scope: "app" },
  { key: "govee.lan.discovery.globalBroadcast", type: "boolean", defaultRaw: "true", unit: "bool", range: "", receipt: "govee2mqtt", liveSafe: false, scope: "app" },
  { key: "govee.lan.discovery.scanList", type: "json", defaultRaw: "[]", unit: "IPs or hostnames", range: "", receipt: "govee2mqtt `GOVEE_LAN_SCAN`", liveSafe: false, scope: "app" },
  { key: "govee.lan.discovery.retryInitialMs", type: "number", defaultRaw: "2000", unit: "ms", range: "", receipt: "govee2mqtt `lan_api.rs:521`", liveSafe: true, scope: "app" },
  { key: "govee.lan.discovery.retryMaxMs", type: "number", defaultRaw: "60000", unit: "ms", range: "", receipt: "govee2mqtt `lan_api.rs:522`", liveSafe: true, scope: "app" },
  { key: "govee.lan.discovery.backgroundRescanMs", type: "number", defaultRaw: "30000", unit: "ms", range: "", receipt: "unmeasured (Lightwave 15 s, HA 300 s)", liveSafe: true, scope: "app" },
  { key: "govee.lan.status.retryMs", type: "number", defaultRaw: "350", unit: "ms", range: "", receipt: "govee2mqtt `lan_api.rs:605`", liveSafe: true, scope: "app" },
  { key: "govee.lan.status.deadlineMs", type: "number", defaultRaw: "10000", unit: "ms", range: "", receipt: "govee2mqtt `lan_api.rs:601`", liveSafe: true, scope: "app" },
  { key: "govee.lan.arm.settleMsDefault", type: "number", defaultRaw: "50", unit: "ms", range: "", receipt: "toolkit measurements default", liveSafe: false, scope: "app" },
  { key: "govee.lan.stream.fallbackHz", type: "number", defaultRaw: "10", unit: "Hz", range: "", receipt: "toolkit `FALLBACK_HZ`", liveSafe: false, scope: "app" },
  { key: "govee.lan.stream.targetHz", type: "number", defaultRaw: "60", unit: "Hz", range: "", receipt: "spec 117 logical rate; per device capped by qualification", liveSafe: false, scope: "app" },
  { key: "govee.lan.stream.keepaliveMs", type: "string", defaultRaw: "0 (off)", unit: "ms", range: "", receipt: "only if qualification shows the unit drops an idle stream", liveSafe: false, scope: "app" },
  { key: "govee.lan.stream.maxRearmAttempts", type: "number", defaultRaw: "3", unit: "count", range: "", receipt: "unmeasured (spec 147 \"do not spam\")", liveSafe: true, scope: "app" },
  { key: "govee.lan.stream.rearmWindowMs", type: "number", defaultRaw: "60000", unit: "ms", range: "", receipt: "unmeasured", liveSafe: true, scope: "app" },
  { key: "govee.lan.command.minSpacingMs", type: "number", defaultRaw: "40", unit: "ms", range: "", receipt: "unmeasured (toolkit: third back-to-back command dropped)", liveSafe: false, scope: "app" },
  { key: "govee.lan.reconnect.maxMs", type: "number", defaultRaw: "5000", unit: "ms", range: "", receipt: "unmeasured target", liveSafe: true, scope: "app" },
  { key: "govee.lan.backoff.minFps", type: "number", defaultRaw: "5", unit: "fps", range: "", receipt: "was hardcoded (`govee/src/index.ts:213`)", liveSafe: true, scope: "app" },
  { key: "govee.brightness.maxPerMinute", type: "number", defaultRaw: "6", unit: "commands", range: "", receipt: "unmeasured (spec 50 \"slow\")", liveSafe: true, scope: "app" },
  { key: "govee.identify.flashMs", type: "number", defaultRaw: "1000", unit: "ms", range: "", receipt: "comment intent in `show-service.ts:101`", liveSafe: true, scope: "app" },
  { key: "govee.testChase.stepMs", type: "number", defaultRaw: "150", unit: "ms", range: "", receipt: "unmeasured", liveSafe: true, scope: "app" },
  { key: "govee.ble.backend", type: "string", defaultRaw: "auto", unit: "enum DS-04", range: "", receipt: "owner", liveSafe: false, scope: "app" },
  { key: "govee.ble.encryptedLink", type: "string", defaultRaw: "auto", unit: "enum DS-05", range: "", receipt: "owner decision", liveSafe: false, scope: "app" },
  { key: "govee.ble.writeBudgetHzDefault", type: "number", defaultRaw: "100", unit: "Hz", range: "", receipt: "toolkit `devices/H61A0.yaml:273` (one unit)", liveSafe: false, scope: "app" },
  { key: "govee.ble.writeDrainMsDefault", type: "number", defaultRaw: "300", unit: "ms", range: "", receipt: "unmeasured (toolkit says measure per unit)", liveSafe: false, scope: "app" },
  { key: "govee.ble.scanTimeoutMs", type: "number", defaultRaw: "10000", unit: "ms", range: "", receipt: "unmeasured", liveSafe: true, scope: "app" },
  { key: "govee.ble.colorQuantizeLevels", type: "string", defaultRaw: "0 (off)", unit: "levels per channel", range: "", receipt: "unmeasured", liveSafe: true, scope: "app" },
  { key: "govee.ble.hostColorChannel", type: "boolean", defaultRaw: "true", unit: "bool", range: "", receipt: "toolkit ble.md section 8", liveSafe: true, scope: "app" },
  { key: "govee.matter.enabled", type: "boolean", defaultRaw: "false", unit: "bool", range: "", receipt: "owner decision per device", liveSafe: false, scope: "app" },
  { key: "govee.matter.commandRateHz", type: "number", defaultRaw: "10", unit: "Hz", range: "", receipt: "unmeasured", liveSafe: true, scope: "app" },
  { key: "govee.cloud.enabled", type: "boolean", defaultRaw: "false", unit: "bool", range: "", receipt: "spec 148", liveSafe: false, scope: "app" },
  { key: "govee.cloud.perDevicePerMinute", type: "number", defaultRaw: "10", unit: "requests", range: "", receipt: "Govee docs via toolkit `cloud.md:102`", liveSafe: false, scope: "app" },
  { key: "govee.cloud.perAccountPerDay", type: "number", defaultRaw: "10000", unit: "requests", range: "", receipt: "Govee docs via toolkit `cloud.md:101`", liveSafe: false, scope: "app" },
  { key: "govee.failover.policy", type: "string", defaultRaw: "hybrid", unit: "enum DS-03", range: "", receipt: "owner", liveSafe: false, scope: "app" },
  { key: "govee.failover.lanLossMs", type: "number", defaultRaw: "3000", unit: "ms", range: "", receipt: "unmeasured", liveSafe: true, scope: "app" },
  { key: "govee.failover.probeIntervalMs", type: "number", defaultRaw: "10000", unit: "ms", range: "", receipt: "unmeasured", liveSafe: true, scope: "app" },
  { key: "govee.device.<fixtureId>.transportMode", type: "string", defaultRaw: "hybrid", unit: "enum DS-31", range: "", receipt: "owner (per device)", liveSafe: true, scope: "device" },
  { key: "govee.device.<fixtureId>.transportOrder", type: "json", defaultRaw: "[\"lan-razer\",\"ble-segmented\",\"lan-json\",\"ble-single\",\"matter\"]", unit: "ordered list", range: "", receipt: "spec 148", liveSafe: true, scope: "device" },
  { key: "live.provider", type: "string", defaultRaw: "fusion", unit: "enum DS-01", range: "", receipt: "owner", liveSafe: false, scope: "app" },
  { key: "live.provider.staleMs", type: "number", defaultRaw: "500", unit: "ms", range: "", receipt: "spec 105", liveSafe: true, scope: "app" },
  { key: "live.rkbx.oscBind", type: "string", defaultRaw: "127.0.0.1:4460", unit: "host:port", range: "", receipt: "rkbx_link README default destination", liveSafe: false, scope: "app" },
  { key: "live.rkbx.configPath", type: "string", defaultRaw: "\"\"", unit: "path to user's rkbx_link folder", range: "", receipt: "user", liveSafe: false, scope: "app" },
  { key: "live.prolink.mode", type: "string", defaultRaw: "passive", unit: "enum DS-29", range: "", receipt: "owner", liveSafe: false, scope: "app" },
  { key: "live.prolink.deviceNumber", type: "number", defaultRaw: "7", unit: "1 to 15", range: "", receipt: "unmeasured (must not collide with real players)", liveSafe: false, scope: "app" },
  { key: "live.prolink.keepaliveMs", type: "number", defaultRaw: "1500", unit: "ms", range: "", receipt: "dysentery analysis", liveSafe: false, scope: "app" },
  { key: "live.prolink.peerExpiryMs", type: "number", defaultRaw: "5000", unit: "ms", range: "", receipt: "unmeasured", liveSafe: true, scope: "app" },
  { key: "live.ax.intervalMs", type: "number", defaultRaw: "250", unit: "ms", range: "", receipt: "unmeasured (was 1000)", liveSafe: true, scope: "app" },
  { key: "live.ax.timeoutMs", type: "number", defaultRaw: "2000", unit: "ms", range: "", receipt: "unmeasured (was 8000)", liveSafe: true, scope: "app" },
  { key: "live.agentApi.port", type: "number", defaultRaw: "30001", unit: "port", range: "", receipt: "rkbx_os2l README, capture log", liveSafe: false, scope: "app" },
  { key: "live.os2l.enabled", type: "boolean", defaultRaw: "true", unit: "bool", range: "", receipt: "owner notes", liveSafe: false, scope: "app" },
  { key: "live.link.enabled", type: "boolean", defaultRaw: "true", unit: "bool", range: "", receipt: "spec 10", liveSafe: false, scope: "app" },
  { key: "live.link.quantum", type: "number", defaultRaw: "4", unit: "beats", range: "", receipt: "Ableton Link default", liveSafe: true, scope: "app" },
  { key: "live.memoryReader.enabled", type: "boolean", defaultRaw: "false", unit: "bool", range: "", receipt: "owner consent required", liveSafe: false, scope: "app" },
  { key: "live.memoryReader.offsetsFile", type: "string", defaultRaw: "<userData>/offsets/rekordbox.json", unit: "path", range: "", receipt: "T-LIVE-11", liveSafe: false, scope: "app" },
  { key: "live.lighting.enabled", type: "boolean", defaultRaw: "true", unit: "bool", range: "", receipt: "spec 7", liveSafe: false, scope: "app" },
  { key: "live.fusion.authority", type: "json", defaultRaw: "[\"lighting-ipc\",\"memory-cleanroom\",\"rkbx-osc\",\"prolink\",\"composite-flx4\",\"ax\",\"os2l\"]", unit: "ordered list", range: "", receipt: "spec 7 extended by owner", liveSafe: true, scope: "app" },
  { key: "live.fusion.disagreeBeats", type: "number", defaultRaw: "0.25", unit: "beats", range: "", receipt: "unmeasured", liveSafe: true, scope: "app" },
  { key: "live.fusion.switchHoldMs", type: "number", defaultRaw: "500", unit: "ms", range: "", receipt: "unmeasured", liveSafe: true, scope: "app" },
  { key: "live.rkbx.playingEpsilonMs", type: "number", defaultRaw: "5", unit: "ms", range: "", receipt: "unmeasured", liveSafe: true, scope: "app" },
  { key: "live.rkbx.pauseHoldMs", type: "number", defaultRaw: "150", unit: "ms", range: "", receipt: "unmeasured", liveSafe: true, scope: "app" },
  { key: "live.prolink.interfaces", type: "json", defaultRaw: "[] (all eligible)", unit: "list", range: "", receipt: "spec 111", liveSafe: false, scope: "app" },
  { key: "live.ax.cpuBudgetPercent", type: "number", defaultRaw: "3", unit: "percent", range: "", receipt: "unmeasured", liveSafe: true, scope: "app" },
  { key: "live.composite.openFilePollMs", type: "number", defaultRaw: "500", unit: "ms", range: "", receipt: "unmeasured", liveSafe: true, scope: "app" },
  { key: "live.composite.correlationWindowMs", type: "number", defaultRaw: "4000", unit: "ms", range: "", receipt: "unmeasured", liveSafe: true, scope: "app" },
  { key: "live.composite.lockedErrorMs", type: "number", defaultRaw: "15", unit: "ms", range: "", receipt: "unmeasured target", liveSafe: true, scope: "app" },
  { key: "live.link.mode", type: "string", defaultRaw: "auto", unit: "enum DS-36", range: "", receipt: "license constraint", liveSafe: false, scope: "app" },
  { key: "live.link.publish", type: "boolean", defaultRaw: "false", unit: "bool", range: "", receipt: "owner", liveSafe: true, scope: "app" },
  { key: "flx4.backend", type: "string", defaultRaw: "auto", unit: "enum DS-13", range: "", receipt: "owner", liveSafe: false, scope: "app" },
  { key: "flx4.portMatch", type: "string", defaultRaw: "DDJ-FLX4", unit: "regex", range: "", receipt: "device name", liveSafe: false, scope: "app" },
  { key: "flx4.tempoRange", type: "string", defaultRaw: "source", unit: "enum source, 6, 10, 16, wide", range: "", receipt: "Rekordbox tempo range setting", liveSafe: true, scope: "app" },
  { key: "flx4.hotplugPollMs", type: "number", defaultRaw: "2000", unit: "ms", range: "", receipt: "unmeasured", liveSafe: true, scope: "app" },
  { key: "flx4.hints.filterWindowMs", type: "number", defaultRaw: "1500", unit: "ms", range: "", receipt: "unmeasured", liveSafe: true, scope: "app" },
  { key: "flx4.hints.enabled", type: "string", defaultRaw: "all hint types", unit: "list", range: "", receipt: "spec 11", liveSafe: true, scope: "app" },
  { key: "serato.remote.enabled", type: "boolean", defaultRaw: "true", unit: "bool", range: "", receipt: "spec 3.1", liveSafe: false, scope: "app" },
  { key: "serato.master.inferHoldMs", type: "number", defaultRaw: "750", unit: "ms", range: "", receipt: "unmeasured", liveSafe: true, scope: "app" },
  { key: "library.rekordbox.reader", type: "string", defaultRaw: "auto", unit: "enum DS-15", range: "", receipt: "owner", liveSafe: false, scope: "app" },
  { key: "library.watch.debounceMs", type: "number", defaultRaw: "2000", unit: "ms", range: "", receipt: "unmeasured", liveSafe: true, scope: "app" },
  { key: "library.watch.engine", type: "string", defaultRaw: "auto", unit: "enum DS-35", range: "", receipt: "owner", liveSafe: false, scope: "app" },
  { key: "library.watch.pollMs", type: "number", defaultRaw: "60000", unit: "ms", range: "", receipt: "unmeasured", liveSafe: true, scope: "app" },
  { key: "library.fileHash.strategy", type: "string", defaultRaw: "full", unit: "enum full, sampled", range: "", receipt: "spec 12", liveSafe: false, scope: "app" },
  { key: "library.rekordbox.dbPath", type: "string", defaultRaw: "auto-detected", unit: "path", range: "", receipt: "rekordbox-connect detection", liveSafe: false, scope: "app" },
  { key: "library.rekordbox.optionsPath", type: "string", defaultRaw: "auto-detected", unit: "path", range: "", receipt: "rekordbox-connect detection", liveSafe: false, scope: "app" },
  { key: "library.rekordbox.sharePath", type: "string", defaultRaw: "auto-detected", unit: "path", range: "", receipt: "rekordbox-connect detection", liveSafe: false, scope: "app" },
  { key: "library.rekordbox.crossCheck", type: "boolean", defaultRaw: "true", unit: "bool", range: "", receipt: "DS-15 combined mode", liveSafe: false, scope: "app" },
  { key: "library.serato.root", type: "string", defaultRaw: "auto-detected (~/Music/_Serato_)", unit: "path", range: "", receipt: "serato-connect, Serato docs", liveSafe: false, scope: "app" },
  { key: "identity.fingerprint.mode", type: "string", defaultRaw: "both", unit: "enum DS-34", range: "", receipt: "spec 12", liveSafe: false, scope: "app" },
  { key: "identity.fingerprint.acousticThreshold", type: "number", defaultRaw: "0.9", unit: "similarity", range: "", receipt: "unmeasured", liveSafe: false, scope: "app" },
  { key: "contracts.mapping.benchMs", type: "number", defaultRaw: "250", unit: "ms per million mappings", range: "", receipt: "unmeasured target", liveSafe: false, scope: "app" },
  { key: "room.distanceMetric", type: "string", defaultRaw: "auto", unit: "enum DS-24", range: "", receipt: "owner room request", liveSafe: true, scope: "app" },
  { key: "room.perimeter.zero", type: "string", defaultRaw: "dj-nearest", unit: "enum DS-25", range: "", receipt: "owner room request", liveSafe: true, scope: "app" },
  { key: "room.perimeter.direction", type: "string", defaultRaw: "clockwise", unit: "enum clockwise, counterclockwise", range: "", receipt: "owner", liveSafe: true, scope: "app" },
  { key: "room.pivot", type: "string", defaultRaw: "room-center", unit: "enum room-center, dj, anchor id", range: "", receipt: "owner", liveSafe: true, scope: "app" },
  { key: "room.sides.centerBandWidth", type: "number", defaultRaw: "0.15", unit: "fraction of room width", range: "", receipt: "unmeasured", liveSafe: true, scope: "app" },
  { key: "room.splits.defaultAngleDeg", type: "number", defaultRaw: "0", unit: "degrees from DJ facing", range: "", receipt: "owner", liveSafe: true, scope: "app" },
  { key: "room.splits.mode", type: "string", defaultRaw: "blend", unit: "enum DS-33", range: "", receipt: "owner room request", liveSafe: true, scope: "app" },
  { key: "room.splits.featherMeters", type: "number", defaultRaw: "0.25", unit: "m", range: "", receipt: "unmeasured", liveSafe: true, scope: "app" },
  { key: "room.zones.featherMeters", type: "number", defaultRaw: "0.2", unit: "m", range: "", receipt: "unmeasured", liveSafe: true, scope: "app" },
  { key: "room.orbit.path", type: "string", defaultRaw: "auto", unit: "enum DS-32", range: "", receipt: "owner room request", liveSafe: true, scope: "app" },
  { key: "room.orientation.leftRightFrom", type: "string", defaultRaw: "dj", unit: "enum dj, audience", range: "", receipt: "spec 40", liveSafe: true, scope: "app" },
  { key: "room.nearDj.radiusMeters", type: "number", defaultRaw: "1.5", unit: "m", range: "", receipt: "unmeasured", liveSafe: true, scope: "app" },
  { key: "venue.spline.toleranceMeters", type: "number", defaultRaw: "0.005", unit: "m", range: "", receipt: "unmeasured", liveSafe: false, scope: "app" },
  { key: "venue.fields.budgetMs", type: "number", defaultRaw: "20", unit: "ms for 2,000 cells", range: "", receipt: "unmeasured target", liveSafe: false, scope: "app" },
  { key: "storage.driver", type: "string", defaultRaw: "auto", unit: "enum DS-06", range: "", receipt: "owner", liveSafe: false, scope: "app" },
  { key: "storage.sqlite.synchronous", type: "string", defaultRaw: "NORMAL", unit: "enum OFF, NORMAL, FULL", range: "", receipt: "SQLite WAL guidance", liveSafe: false, scope: "app" },
  { key: "storage.sqlite.busyTimeoutMs", type: "number", defaultRaw: "5000", unit: "ms", range: "", receipt: "unmeasured", liveSafe: false, scope: "app" },
  { key: "ops.safeState.look", type: "string", defaultRaw: "ending-look", unit: "enum hold-last, ending-look, blackout", range: "", receipt: "spec 133", liveSafe: true, scope: "app" },
  { key: "diagnostics.mode", type: "string", defaultRaw: "normal", unit: "enum normal, diagnostic", range: "", receipt: "spec 102, 130", liveSafe: true, scope: "app" },
  { key: "diagnostics.log.maxFileMb", type: "number", defaultRaw: "10", unit: "MB", range: "", receipt: "unmeasured", liveSafe: false, scope: "app" },
  { key: "diagnostics.log.files", type: "number", defaultRaw: "5", unit: "count", range: "", receipt: "unmeasured", liveSafe: false, scope: "app" },
  { key: "diagnostics.recorder.enabled", type: "boolean", defaultRaw: "false", unit: "bool", range: "", receipt: "spec 103", liveSafe: true, scope: "app" },
  { key: "diagnostics.recorder.maxMb", type: "number", defaultRaw: "512", unit: "MB", range: "", receipt: "unmeasured", liveSafe: false, scope: "app" },
  { key: "security.cloudAllowed", type: "boolean", defaultRaw: "false", unit: "bool", range: "", receipt: "spec 110", liveSafe: false, scope: "app" },
  { key: "update.checkOnLaunch", type: "boolean", defaultRaw: "false", unit: "bool", range: "", receipt: "spec 145", liveSafe: false, scope: "app" },
  { key: "update.neverDuringLive", type: "string", defaultRaw: "read-only invariant", unit: "", range: "", receipt: "spec 145", liveSafe: false, scope: "app" },
  { key: "ui.shortcuts.*", type: "string", defaultRaw: "B blackout, W white, F freeze, A auto, M manual, Up and Down master, 1 to 9 presets", unit: "map", range: "", receipt: "spec 94", liveSafe: true, scope: "app" },
  { key: "ui.shortcuts.whiteMode", type: "string", defaultRaw: "hold", unit: "enum hold, toggle", range: "", receipt: "owner", liveSafe: true, scope: "app" },
  { key: "ui.live.minTimingFontPx", type: "number", defaultRaw: "48", unit: "px", range: "", receipt: "spec 143", liveSafe: true, scope: "app" },
  { key: "ui.live.minBodyFontPx", type: "number", defaultRaw: "16", unit: "px", range: "", receipt: "spec 143", liveSafe: true, scope: "app" },
  { key: "qa.events.toleranceBeats", type: "number", defaultRaw: "1", unit: "beats", range: "", receipt: "unmeasured target", liveSafe: false, scope: "app" },
  { key: "qa.events.minRecall", type: "string", defaultRaw: "per event type map, 0.8 default", unit: "ratio", range: "", receipt: "unmeasured target", liveSafe: false, scope: "app" },
  { key: "qa.events.minPrecision", type: "string", defaultRaw: "per event type map, 0.7 default", unit: "ratio", range: "", receipt: "unmeasured target", liveSafe: false, scope: "app" },
  { key: "qa.key.minAccuracy", type: "number", defaultRaw: "0.7", unit: "ratio", range: "", receipt: "unmeasured target", liveSafe: false, scope: "app" },
  { key: "qa.replay.timeToleranceMs", type: "number", defaultRaw: "5", unit: "ms", range: "", receipt: "unmeasured target", liveSafe: false, scope: "app" },
  { key: "qa.faults.*", type: "string", defaultRaw: "scenario parameter maps", unit: "map", range: "", receipt: "spec 104 to 107", liveSafe: false, scope: "app" },
  { key: "qa.perf.ciSlack", type: "number", defaultRaw: "3", unit: "multiplier on reference thresholds", range: "", receipt: "CI runner variance", liveSafe: false, scope: "app" },
  { key: "qa.soak.maxMemSlopeMbPerHour", type: "number", defaultRaw: "5", unit: "MB per hour", range: "", receipt: "spec 125 \"no growth trend\"", liveSafe: false, scope: "app" },
  { key: "qa.soak.maxLatencySlopeMsPerHour", type: "number", defaultRaw: "1", unit: "ms per hour", range: "", receipt: "spec 125", liveSafe: false, scope: "app" },
  { key: "qa.sync.maxBeatErrorMs", type: "number", defaultRaw: "20", unit: "ms p95", range: "", receipt: "unmeasured target", liveSafe: false, scope: "app" },
  { key: "qa.validation.minPerCategory", type: "number", defaultRaw: "3", unit: "tracks", range: "", receipt: "spec 116", liveSafe: false, scope: "app" },
] as const;

export type ConfigKey = (typeof KEYS)[number]["key"];

const byKey = new Map(KEYS.map((k) => [k.key, k]));

export function defineKey(key: string): KeyDef {
  const def = byKey.get(key);
  if (!def) throw new Error(`unknown-config-key: ${key}`);
  return def;
}

export function defaultFor(key: string): unknown {
  const def = defineKey(key);
  if (def.type === "boolean") return def.defaultRaw === "true";
  if (def.type === "number") return Number(def.defaultRaw);
  if (def.type === "json") { try { return JSON.parse(def.defaultRaw); } catch { return def.defaultRaw; } }
  return def.defaultRaw;
}

export function defaultsObject(): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  for (const k of KEYS) out[k.key] = defaultFor(k.key);
  return out;
}

export const defaultsSchema = z.record(z.string(), z.unknown());
